port: 8080

resend_api_key: ''

# Database configuration
# Options: SQLite, MySQL, PostgreSQL, h2
database:
  type: SQLite
  host: localhost:0808
  database: sieadev
  credentials: # Not required for SQLite
    username: root
    password: password